# Generated by Django 6.0.3 on 2026-03-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processed", "Processed"),
                    ("failed", "Failed"),
                ],
                db_default="pending",
                max_length=20,
            ),
        ),
    ]
