# Generated by Django 6.0.3 on 2026-03-09 01:43

import django.db.models.deletion
import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0002_enrollment_status"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="status",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EnrollmentBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        db_default="pending",
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("processed_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("task_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "EnrollmentBatch",
                "verbose_name_plural": "EnrollmentBatches",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="batch_status_created_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="enrollment",
            name="batch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch",
                to="enrollments.enrollmentbatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("batch", "student_id"), name="unique_enrollment_per_batch"
            ),
        ),
    ]
