# Generated by Django 6.0.3 on 2026-03-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "enrollments",
            "0003_remove_enrollment_status_enrollment_error_message_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("progress", "Progress"),
                    ("processed", "Processed"),
                    ("failed", "Failed"),
                    ("partial", "Partial"),
                ],
                db_default="pending",
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("progress", "Progress"),
                    ("processed", "Processed"),
                    ("failed", "Failed"),
                    ("partial", "Partial"),
                ],
                db_default="pending",
                db_index=True,
                max_length=16,
            ),
        ),
    ]
